### ISSUE TITLE
Implement application level build

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/ufs-coastal-app#1]
@saeed-moghimi-noaa @pvelissariou1 I created initial version of app level build system and tested with different configuration. It seems it is working but we could improve it along the development. As an example, FVCOM case can be build like following

```
./build.sh -p=orion -a=CSTLF -v
```

At this point, it will only work with certain apps but once we have a capability of creating single executable, it would be much more easier. I'll also populate the README.md file with some basic build instruction. We could point user to Sphinx documentation for detailed information. I am also planing to include option to build dependencies using spack-stack. I''ll keep you posted about it. We could use this thread to discuss app level build related development.

**Comment by saeed-moghimi-noaa** [comment]
Thanks @uturuncoglu . Highly appreciated.

**Comment by janahaddad** [comment]
Closing with #3
