### ISSUE TITLE
Clarify license for ufs-coastal-app and relationship to component model licenses

### ISSUE THREAD

**Issue by dpsnowden** [oceanmodeling/ufs-coastal-app#4]
I'm on the writing team for the NOAA report to Congress on the progress [LEGEND Act](https://www.congress.gov/bill/117th-congress/senate-bill/1127) implementation.  The LEGEND Act is primarily focused on making NOAA models publicly available and encouraging open development.  There is a section on Licensing and I came to this repo to see how we've licensed UFS Coastal.  

This repo doesn't have a license.  Understandable, given that it's mostly documentation.  But it's also ambiguous.

The ufs-weather-model fork, contains the [License](https://github.com/oceanmodeling/ufs-weather-model/blob/feature/coastal_app/LICENSE.md) for that model suite that includes the a nice description of the different licenses for the component models.  Unfortunately, none of the Ocean components are included.  

Independently, @saeed-moghimi-noaa has provided a summary of the component model licenses, but since it's buried ina Google Doc it's not visible to the community.  What are your thoughts on clarifying this?  

Would any or all of these approaches work?
- License the documentation repo and create an elaborate LICENSE.md explaining all the components?
- Submit a PR to the ufs-weather-model adding the ocean model licensing details to that?
- ?

FWIW, this is what I currently have about the ocean model licenses: 

Model | Status
-- | --
ADCIRC | The ADCIRC source code is copyrighted, 1994-2016, by: R.A. Luettich, Jr. and J.J. Westerink
DFLOW | License type: GNU AGPL (GNU Affero General Public License) https://www.gnu.org/licenses/agpl-3.0.en.html
FVCOM | http://fvcom.smast.umassd.edu/FVCOM/Source/agreement.htm
ROMS | MIT open-source license (https://www.myroms.org/index.php?page=License_ROMS)
SCHISM | Apache-2.0 License (https://github.com/schism-dev/schism)
SLOSH | License cleared by NOAA General Council - Apr 23, 2014.  Summary: Provided "as is". NOAA assumes no legal liability. NOAA with not provide technical support or training unless a separate agreement is in place SLOSH software is not subject to copyright protection and is considered in the public domain. NOAA requests that recipient acknowledge NOAA's contribution to SLOSH in technical documentation. NOAA encourages recipient to provide NOAA with any improvements

**Comment by janahaddad** [comment]
Hey @dpsnowden thank you! Yes this is a next task:  adding a license.md to this repo, as part of shifting from model-level to this app-level repo as the Project's landing page (https://github.com/oceanmodeling/ufs-weather-model/issues/71)

We have a [draft](https://docs.google.com/document/d/1tL9mwp1iNF3Jef3bwlHLbugOF7o4sTX-43kKTGO2g3M/edit) to work from developed by @pvelissariou1. I'll incorporate your feedback there. Thanks for helping us push this forward!

**Comment by janahaddad** [comment]
Closing this issue with just-added LICENSE.md
